### ISSUE TITLE
[Generator] property_path = FALSE

### ISSUE THREAD

**Issue by recipe** [Abhoryo/APYJsFormValidationBundle#13]
When field's property_path is false we need to exclude it from form validation on client-side. Symfony itself does not apply validation constraints that are set for the field with property_path = FALSE
Any objections [agree, disagree]?

[form Field Type - property-path](http://symfony.com/doc/master/reference/forms/types/form.html#property-path)

**Comment by Abhoryo** [comment]
Agree.

**Comment by recipe** [comment]
It has been fixed.
