### ISSUE TITLE
phpunit tests should be implemented

### ISSUE THREAD

**Issue by recipe** [Abhoryo/APYJsFormValidationBundle#15]

**Comment by Abhoryo** [comment]
Is it really possible with the dynamic javascript or do you just test that the javascript script is present ?

**Comment by recipe** [comment]
I am going to cover php classes at first. For the generated javascript files we could use functional tests. (Regular expression would check that certain constraints were added.)

**Comment by recipe** [comment]
All changes will be in the branch [ticket_15](https://github.com/recipe/APYJsFormValidationBundle/tree/ticket_15)

**Comment by Abhoryo** [comment]
Ok

**Comment by recipe** [comment]
Set the boll rolling.
