### ISSUE TITLE
[javascript] several forms on one page simultaneously.

### ISSUE THREAD

**Issue by recipe** [Abhoryo/APYJsFormValidationBundle#20]
We must do refactoring of the jsfv object. We should create one common object.
jsfv global object must be unique, but it should register handlers from all forms. 

var jsfv = new function ()

**Comment by recipe** [comment]
Also we need to change assetic cached file name. that shoud be suffixed with the formType->get('name') default ('form')

{routename}_{formname}.js

P/s I fixed second point on my own, as it had been critical for test. [view changes](https://github.com/Abhoryo/APYJsFormValidationBundle/commit/7516250e539ed94e465a8094852de7640d0c14c7)

**Comment by recipe** [comment]
we could wrap this using pattern, at least.

```
jQuery(function(){
     var jsfv = new function .... 
})
```

I do not know how about another frameworks.

**Comment by Abhoryo** [comment]
To do the onReady handler ?

**Comment by recipe** [comment]
Yes. Two variants:
1) we put jsfv object into function's visibility scope to avoid conflicts in global scope.
or
2) refactoring of the code. common part javascript jsfv  +  form handlers parts jsfv.addHandler(formObject)

**Comment by beepsoft** [comment]
Hi,

I would also like to have JS validation for my embedded forms. My current workaround is that for each embedded from I call {{ JSFV(embedded_form) }} and I have a customized  JsFormValidation.js.twig where the jsfv is suffixed as jsfv{{formName}} (actually I hacked FormValidationScriptGenerator::generate to pass the form's id as formId and I use that as a suffix liek jsfv{{formId}}). Of course, this generates a lot of unnecessary replica of the same script and it doesn't work for forms generated from prototype.

Do you have plans to add this refactored jsfv() to handle these embedded form use cases?

**Comment by Abhoryo** [comment]
Right now, non. I really don't have time to update this bundle.

**Comment by recipe** [comment]
Thanks to Ton it's fixed.

**Comment by Abhoryo** [comment]
Thx
