### ISSUE TITLE
buildForm() must be compatible

### ISSUE THREAD

**Issue by mjuchli** [Abhoryo/APYJsFormValidationBundle#25]
Hi there,

I use symfony 2.0.15 and get following error:

Fatal error: Declaration of APY\JsFormValidationBundle\Form\Extension\FormTypeExtension::buildForm() must be compatible with Symfony\Component\Form\FormTypeExtensionInterface::buildForm(Symfony\Component\Form\FormBuilder $builder, array $options) in /...pwd.../vendor/bundles/APY/JsFormValidationBundle/Form/Extension/FormTypeExtension.php on line 104

Deps:

[JsFormValidationBundle]
    git=git://github.com/Abhoryo/APYJsFormValidationBundle.git
    target=bundles/APY/JsFormValidationBundle
    version=2.0

Also tried:

[JsFormValidationBundle]
    git=git://github.com/Abhoryo/APYJsFormValidationBundle.git
    target=bundles/APY/JsFormValidationBundle

Any ideas?

**Comment by Abhoryo** [comment]
https://github.com/Abhoryo/APYJsFormValidationBundle/blob/2.0/Form/Extension/FormTypeExtension.php

In 2.0 branch buildform isn't override so you can't have this error.

I don't know how to get the 2.0 version with deps but in your case it's not working.

**Comment by recipe** [comment]
We should update our branch accordingly

https://github.com/symfony/symfony/blob/2.0/src/Symfony/Component/Form/FormTypeInterface.php

They did changes

**Comment by Abhoryo** [comment]
`buildform` method isn't overrided in the 2.0 branch!

**Comment by mjuchli** [comment]
Shame on me.
I didn't recognize the deps.lock file where master was still added.

Sorry for that.
