### ISSUE TITLE
unable find template

### ISSUE THREAD

**Issue by Barno** [Abhoryo/APYJsFormValidationBundle#32]
i follow the example but i have this error before render the form's page

Unable to find template "APYJsFormValidationBundle:Constraints:CountValidator.js.twig" in APYJsFormValidationBundle::JsFormValidation.js.twig at line 52.

**Comment by Abhoryo** [comment]
The bundle isn't update with the last symfony constraints.

For now you can add a file CountValidator.js.twig in APYJsFormValidationBundle/Resources/views/Constraints/ with the following content:

```
function Count(field, params)
{
    var value = field && field.nodeName ? {{ getJsFormElementValue('field') }} : field;

    return true;
}
```

**Comment by Barno** [comment]
Thank you, it's works
