### ISSUE TITLE
RangeValidator

### ISSUE THREAD

**Issue by Erathian** [Abhoryo/APYJsFormValidationBundle#34]
Hi, I'm getting: Unable to find template "APYJsFormValidationBundle:Constraints:RangeValidator.js.twig" so I found out that Range Validator is missing. Is there any chance of this being added or I should use Min/Max constraints instead (they will be deprecated soon though)? Thanks for reply :-)

**Comment by recipe** [comment]
Please look at #32 You can find out some answer on your question. Bundle hasn't been updated yet with the new constraints from 2.2 version of symfony. However you may add it yourself.

**Comment by recipe** [comment]
RangeValidator has been provided.
