### ISSUE TITLE
Incompatible with BazingaExposeTranslationBundle 0.3?

### ISSUE THREAD

**Issue by friederschueler** [Abhoryo/APYJsFormValidationBundle#38]
I installed Bazinga with:

> php composer.phar require willdurand/expose-translation-bundle

I typed "*" for the version constraint and it installed 0.3. Unfortunately it seems that  APYJsFormValidationBundle is not compatible to it:

> php composer.phar require "apy/jsfv-bundle":"dev-master"

Problem 1
    - Can only install one of: willdurand/expose-translation-bundle[0.2.1, 0.3.0].
    - Can only install one of: willdurand/expose-translation-bundle[0.3.0, 0.2.1].
    - apy/jsfv-bundle dev-master requires willdurand/expose-translation-bundle >=0.2.1,<0.3

Is that true or a mistake < instead of <=?

Bug: Installation as described in the documentation will fail.

> symfony/symfony v2.2.2 The Symfony PHP framework
> willdurand/expose-translation-bundle 0.3.0

**Comment by recipe** [comment]
We have not tested yet with 0.3. BazingaExpose's composer.json dev-master refers to 0.2.x-dev. 
https://github.com/willdurand/BazingaExposeTranslationBundle/blob/master/composer.json

**Comment by recipe** [comment]
I've updated composer.json so that you can use this bundle with 0.3 version of BazingaExpose. If you found any compability issue please open new thread
