### ISSUE TITLE
Failed to create web/bundles/jsformvalidation/js/"

### ISSUE THREAD

**Issue by FredoVelcro-zz** [Abhoryo/APYJsFormValidationBundle#40]
In production environment, i have a 500 server error due to a problem when generating the .js file : 

Failed to create web/bundles/jsformvalidation/js/"

Maybe need automating this ?

**Comment by Abhoryo** [comment]
Maybe add some access to this folder like the log and cache directory of symfony.
You can warm some scripts but you can't warm every scripts for some specific cases.
