### ISSUE TITLE
fix dependency on symfony

### ISSUE THREAD

**Issue by lsmith77** [Abhoryo/APYJsFormValidationBundle#44]
https://github.com/Abhoryo/APYJsFormValidationBundle/blob/master/composer.json#L19

first up i would recommend to depend on framework-bundle instead of symfony itself. furthermore I think it would be safe to mark this bundle as compatible with `symfony/framework-bundle: ~2.3`

**Comment by recipe** [comment]
Travis refuses to digest it. Can't figure out why.
https://travis-ci.org/Abhoryo/APYJsFormValidationBundle/jobs/11481025

**Comment by recipe** [comment]
Does `"symfony/framework-bundle": "~2.1"` mean that we do not support 2.2.\* and 2.3.\* versions of symfony? I think `"symfony/framework-bundle": ">=2.1,<2.4-dev"` would more correct as we support them. Please explain?

**Comment by lsmith77** [comment]
the `~` means that the last number in the following version string can be incremented to any higher number. ie. `~2.1` means `2.1.*`, `2.2.*` etc are allowed .. but `2.0.*` is not

**Comment by recipe** [comment]
ok. This fact seems to be not obvious while reading  http://getcomposer.org/doc/01-basic-usage.md#package-versions
