### ISSUE TITLE
custom constrain, geocomplete plugin from jquery

### ISSUE THREAD

**Issue by bastienEichenberger** [Abhoryo/APYJsFormValidationBundle#53]
Hi all,

First of all, I would like to say thanks you for your great work. Your bundle works fine…

I write an application who use geocomplete plugin from jquery and I have some troubles to translate my javascript to a custom javascript constraint.

I would like to translate this:

<pre><code>
// on the geocode:error event valid display error
$('#fos_user_registration_form_adresse').bind("geocode:error", function(event, result) {
    //display the error
});

 $('#fos_user_registration_form_adresse').bind("geocode:result", function(event, result) {
    //clear the error -> this is ok
 });
</code></pre>

I have no idea how to do this in my twig.js function:

<pre><code>
function IsAdresseValid(field, params)
{
    var value = field && field.nodeName ? {{ getJsFormElementValue('field') }} : field;
    
    if (isNotDefined(value)) {
        return true;
    }
    return getComputeMessage(params.message);
}
</code></pre>

Thanks your for your help.
Have a nice day.

**Comment by Abhoryo** [comment]
This is an error generate by a javascript plugin so I think this has nothing to do with this bundle.
But you can use directly the translator bundle to translate your error messages.

See this [bundle documentation](https://github.com/willdurand/BazingaExposeTranslationBundle/blob/master/Resources/doc/README.markdown)

`Translator.get('key');` with the default domain
