### ISSUE TITLE
Embedded forms

### ISSUE THREAD

**Issue by slurx** [Abhoryo/APYJsFormValidationBundle#54]
Hello, I am new here and I using for first time this bundle. It works fine but when I have an object Class that contains another object inside, the javascript code is not generated.
For Example:
If you have an User object that contains a field like UserProfile object, you define the two Form Classes, i.e. UserType and UserProfileType. Inside UserType buildForm method you call to the UserProfile method:

 public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('username', 'text');
        $builder->add('profile', new ProfileType());
    }

This example doesnt work, not throw any errors however doesnt generate any validation rules in the js file.

Sorry If my english is not correct :-P

Lot of thanks! and well done!!

**Comment by Abhoryo** [comment]
Look the documentation for your symfony version, maybe the validation of subforms isn't set to true.

**Comment by slurx** [comment]
Hi!, thanks for your response, my symfony version is 2.3.8, and in my test code in UserProfileType I set cascade_validation to true, it is necesary anything else?, 

Lot of thanks!

**Comment by Abhoryo** [comment]
I don't know, sorry. Read the RedMe file. Use the other bundle, it should work with your case.

**Comment by slurx** [comment]
Ok, thanks ;-), must I close this issue?

**Comment by Abhoryo** [comment]
No, it's good.
