### ISSUE TITLE
Generated javscript cannot find form

### ISSUE THREAD

**Issue by zd-dalibor** [Abhoryo/APYJsFormValidationBundle#7]
In the file [JsFormValidation.js.twig](https://github.com/Abhoryo/APYJsFormValidationBundle/blob/master/Resources/views/JsFormValidation.js.twig) on line 88 is code:
**code1**

``` javascript
var form = jsfv.id('{{ formName }}');
```

that trays to get form with id equal to form name. My form don't have id equal to form name.

On line 94 is code:
**code2**

``` javascript
form = jsfv.id('ma_form__token').form;
```

that trays to get form by csrf token field if form with **code1** is not found.

First _ma_form__token_ is hardcoded and should be _{{formName}}__token_.
Second what if csrf protection is disabled and there is not csrf token field in form. How in this case we can tell APYJsFormValidationBundle to generate corect script for aur form?

**Comment by Abhoryo** [comment]
Hi,
The default file JsFormValidation.js.twig is made for a default configuration.

For your case, you have to override it. See [Overriding the bundle doc](https://github.com/Abhoryo/APYJsFormValidationBundle/blob/master/Resources/doc/overriding_the_bundle.md)

**Comment by zd-dalibor** [comment]
Thanks. This does the trick.

I also notice that this bundle load validation constraints only from annotations and not from yaml, xml and php formats. Because I use yaml format I had to create my preprocessor event to load constraints in the metadata.

**Comment by Abhoryo** [comment]
Great, I've always wanted to implement a yaml loader but never have the time.

Can you create a PR or bundle with your preprocessor ?
