### ISSUE TITLE
Symfony 2.1 compability issue

### ISSUE THREAD

**Issue by recipe** [Abhoryo/APYJsFormValidationBundle#8]
There are a lot of issues related to transition to symfony 2.1 version. Are you going to perform code changes? Will you maintain this bundle in the future?

**Comment by Abhoryo** [comment]
There are too many changes in the form component of Symfony2.1. It still changes in beta version so I wait for a stable version of Symfony2.1 before the update.

**Comment by recipe** [comment]
Thank you. I like this bundle and I have been using it for my project with symfony 2.1-beta3.  One thing i had to improve it just to add support of entity level constraints such as UniqueEntity, and custom constraints which are based on function. I'm using jquery custom events for binding as well as naming conventions of the javascript handlers. I'll share code in the fork branch lately.

**Comment by Abhoryo** [comment]
Ok.

**Comment by recipe** [comment]
In addition I would not find this bundle in the pakagist.org. You have to add.

**Comment by Abhoryo** [comment]
Yeah for now I wouldn't put it in packagist because It is not compatible with 2.1 and nobody report issues.
